### ISSUE TITLE
setup websocket

### ISSUE THREAD

**Issue by alqa-dash** [ajaysinghthakur/webrtcRTCdataChannel-Video#1]
Hi!

How did you setup server side websocket (self.socket = WebSocket(url: URL(string: "ws://192.168.1.47:9090")!)). I have only kurento websocket but its json-rpc specification doesn't correspond to dict.json which you configured in app. Can you share websocket configuration?

**Comment by ajaysinghthakur** [comment]
go through this tutorial -https://www.tutorialspoint.com/webrtc/webrtc_architecture.htm.
i made the ios side of the app and made node app from above link

**Comment by LorenzoMcMaster** [comment]
hi, 
thanks for making this sample app available. When learning a new techno it's very useful to have a starting point.
I've installed your sample client on my iPhone but now, I've having trouble with the signalling server. It would be nice it you could also share the server side part of your sample app. That way, users could get a fully working sample.

**Comment by ajaysinghthakur** [comment]
Okay, I am traveling I will give you the server side code after the new year.

**Comment by LorenzoMcMaster** [comment]
Thank you very much and happy new year.

**Comment by ajaysinghthakur** [comment]
please see the updated readme docs
